// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/MyComponent.tsx": () => import("../components/mockups/MyComponent.tsx"),
  "./components/mockups/Project1Goodies.tsx": () => import("../components/mockups/Project1Goodies.tsx"),
  "./components/mockups/Project2Anniversary.tsx": () => import("../components/mockups/Project2Anniversary.tsx")
};
